---
- name: Install docker
  gather_facts: No
  hosts: with_ssh
  become: yes

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
        
    - name: Install yum utils
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - podman
          - buildah
     
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    
    - name: Yum update cache
      yum:
        update_cache: yes
        
    - name: Upgrade all packages
      yum:
       name: '*'
       state: latest
           
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
   
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
