---
- name: Install docker
  gather_facts: No
  hosts: with_ssh
  become: yes

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
        
    - name: Delete packages (podman and buildah)
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - podman
          - buildah
     
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    
    - name: Yum update cache
      yum:
        update_cache: yes
        
    - name: Upgrade all packages
      yum:
       name: '*'
       state: latest
           
    - name: Install Docker
      yum:
       name: "{{ packages }}"
       state: latest
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
   
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Enable firewalld
      service: name=firewalld state=started enabled=yes

    - name: Enable masquerade for Docker Networking
      command: firewall-cmd --zone=public --add-masquerade --permanent
    
    - name: Setting up the firewalld
      firewalld:
        zone: public
        masquerade: yes
        permanent: yes 
        state: enabled
      notify:
        - Setting up the firewalld

  handlers:
    - name: Setting up the firewalld
      service:
        name: firewalld
        state: reloaded
